dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

env:
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=nightly  WP_MULTISITE=0

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=1
  allow_failures:
    - php: nightly

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
